Make matrix
damianjilk2/openmc pull request #2
Opened 2024-10-30 14:23 UTC by damianjilk2

# Description

Please include a summary of the change and which issue is fixed if applicable. Please also include relevant motivation and context.

Fixes # (issue)

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [ ] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

2024-10-30 14:28 UTC, damianjilk2 commented
Code to access make_matrix
`import openmc.lib
openmc.lib.init()
start = 10
end = 11
result = openmc.lib.make_matrix(start, end)
openmc.lib.finalize()`

2025-02-02 16:43 UTC, gonuke requested changes
We should focus on getting this merged in the next week or 2 - and then propose a PR to openmc

2025-02-02 16:43 UTC, gonuke commented on openmc/lib/core.py
> +_dll.make_matrix.restrype = None
```suggestion
_dll.make_matrix.restype = None
```

2025-02-02 16:43 UTC, gonuke commented on src/geometry_aux.cpp
> +  }
Might make sense for this to be function that acts on a single start/end pair and then call it from this function

2025-02-02 16:43 UTC, gonuke commented on include/openmc/geometry_aux.h
> +extern "C" void openmc_get_optical_thickness(Position start_voxel_min,
Needs some documentation in comments

2025-02-02 16:43 UTC, gonuke commented on tests/test_openmc_get_optical_thickness.py
> +material = openmc.Material(name="Hydrogen")
We should implement this with fictitious cross-sections that are simple and well-known

2025-02-02 16:43 UTC, gonuke commented on openmc/lib/core.py
> +def get_optical_thickness(start_voxel_min:tuple, start_voxel_max:tuple, end_voxel_min:tuple, end_voxel_max:tuple, num_rays:int):
Given my suggestion to have a new function that just calculates the optical thickness between one start/end pair, we should consider if it should also be exposed in the python API

2025-02-02 16:43 UTC, gonuke commented on src/geometry_aux.cpp
> +      if (boundary.surface_index == -1)
We need an issue to focus on the need to improve/correct this stopping condition.

2025-02-03 23:06 UTC, damianjilk2 commented
A couple of notes:

- there is a message that prints to terminal a lot (I believe whenever a new particle is made) stating "Maximum neutron transport energy: 20000000 eV for H1". This happens with strictly one nuclide per simulation and does not seem to matter which elements are used (for instance, removing the water material results in a uranium isotope in the message). I tracked the message to simulation.cpp but it seems incorrect to simply comment out the warning message to improve performance.
Perhaps this will be fixed with fictitious cross section data. 

- still looking for a way to add weird cells and verify symmetric matrix. `distance_to_boundary(particle)` is doing a lot of the logical heavy lifting but a more thorough verification should be done to ensure gaps in materials are handled as expected.

- previously had a statement disallowing `surface index = -1`. After debugging, I found out that this limitation prevented tau from being symmetric. Still uncertain what this means however. I predict it could be related to incorrectly setting up materials within the .py test but I have not looked into it yet.

2025-02-04 16:52 UTC, pshriwise reviewed
As discussed in-person, calling `openmc.lib.simulation_init` should take care of the warning message you were seeing @damianjilk2.

2025-02-04 16:52 UTC, pshriwise commented on tests/test_openmc_get_optical_thickness.py
> +    openmc.lib.init()
```suggestion
    openmc.lib.init()
    openmc.lib.simiulation_init()
```

2025-02-04 16:52 UTC, pshriwise commented on src/geometry_aux.cpp
> +  initialize_data();
```suggestion
```

2025-02-04 17:23 UTC, gonuke requested changes
The refactor here is good, some follow-on comments to bring this home.

2025-02-04 17:23 UTC, gonuke commented on openmc/lib/core.py
> +def get_optical_thickness(start_voxel_min:tuple, start_voxel_max:tuple, end_voxel_min:tuple, end_voxel_max:tuple, num_rays:int):
I don't think I was clear about this.  You now have `caluclate_optical_thickness` and `get_optical_thickness`. I was suggesting that make both available via the `_dll` - not necessarily that you write a python method (although that may be good, too)

2025-02-04 17:23 UTC, gonuke commented on src/geometry_aux.cpp
> +  Position end_sampled_position, uint64_t* seed)
you don't need a `seed` here
```suggestion
  Position end_sampled_position)
```

2025-02-04 17:23 UTC, gonuke commented on src/geometry_aux.cpp
> +    double distance_to_boundary = boundary.distance;
Don't need to store this `Boundary` object
```suggestion
    double distance_to_boundary = distance_to_boundary(p).distance;
```

2025-02-04 17:23 UTC, gonuke commented on src/geometry_aux.cpp
> +    }
You are doing the `event_calcualte_xs` as well as the incrementing of `optical_thickness` both in this if clause and if you don't follow it.  The logic will be simpler if you move this check to after the ones below and only break if necessary.

Really, this should be an if/else for break vs `move_distance()`

2025-02-04 17:23 UTC, gonuke commented on src/geometry_aux.cpp
> +    if (distance_to_endpoint < distance_to_boundary) {
This stopping condition is a good start.  We'll have to think through some of the pathologies that may occur and write tests to confirm that it works over all those edge cases.

2025-02-04 17:23 UTC, gonuke commented on src/geometry_aux.cpp
> +extern "C" void openmc_get_optical_thickness(Position start_voxel_min,
This function and the previous one have similar names now.  Maybe this one can be renamed to better convey what it's doing.  `get_mean_optical_thickness_between_voxels` or something like that?

2025-02-04 23:11 UTC, damianjilk2 commented on openmc/lib/core.py
> +def get_optical_thickness(start_voxel_min:tuple, start_voxel_max:tuple, end_voxel_min:tuple, end_voxel_max:tuple, num_rays:int):
I will make it accessible to python api as well. We can change after discussing use cases further to determine what should be available

2025-02-04 23:20 UTC, damianjilk2 commented on src/geometry_aux.cpp
> +    }
Good point. However, I don't think it will clean up quite as nice as hoped for since adding to the optical thickness will vary depending on using `distance_to_endpoint` or `distance_to_boundary`

2025-02-04 23:31 UTC, damianjilk2 commented
Optical thickness calculation generated from test file (10,000 rays)

  | Voxel 0 | Voxel 1 | Voxel 2 | Voxel 3 | Voxel 4 | Voxel 5 | Voxel 6 | Voxel 7
-- | -- | -- | -- | -- | -- | -- | -- | --
Voxel 0 | 1.284555 | 1.643602 | 1.64283 | 2.055349 | 1.642064 | 2.054638 | 2.053499 | 2.397973
Voxel 1 | 1.649533 | 0.814222 | 1.882247 | 1.432811 | 1.880309 | 1.432797 | 2.244048 | 1.878883
Voxel 2 | 1.651829 | 1.884811 | 0.814222 | 1.434143 | 1.881751 | 2.246266 | 1.432797 | 1.880147
Voxel 3 | 2.062959 | 1.436233 | 1.435014 | 0.814222 | 2.244596 | 1.881751 | 1.880309 | 1.432797
Voxel 4 | 1.649182 | 1.884225 | 1.883178 | 2.24704 | 0.814222 | 1.434143 | 1.432811 | 1.880851
Voxel 5 | 2.0646 | 1.436183 | 2.247067 | 1.883178 | 1.435014 | 0.814222 | 1.882247 | 1.432811
Voxel 6 | 2.065278 | 2.248764 | 1.436183 | 1.884225 | 1.436233 | 1.884811 | 0.814222 | 1.434143
Voxel 7 | 2.409221 | 1.884315 | 1.884408 | 1.436183 | 1.882323 | 1.436233 | 1.435014 | 0.814222

2025-02-06 15:34 UTC, lewisgross1296 reviewed
`test_openmc_get_optical_thickness.py` should probably live in `tests/unit_tests`, or `tests/regression_tests` if not unit tests. Consider looking at [this test](https://github.com/openmc-dev/openmc/blob/develop/tests/unit_tests/test_geometry.py) for some guidance

2025-02-12 02:02 UTC, gonuke requested changes
This is coming together nicely.

2025-02-12 02:02 UTC, gonuke commented on src/geometry.cpp
> +  Position start_sampled_position, Position end_sampled_position)
Not only does this match your declaration in the header, there may be use cases for this where the positions aren't "sampled"
```suggestion
  Position start_pos, Position end_pos)
```
(and rename all subsequent uses)

2025-02-12 02:02 UTC, gonuke commented on src/geometry.cpp
> +    if (!exhaustive_find_cell(p))
It's inefficient to find the cell each time you cross a surface.  I think you will want to call `Particle::cross_surface()` at the appropriate spot

2025-02-12 02:02 UTC, gonuke commented on src/geometry.cpp
> +    }
This may be where you call `p.cross_surface()`

2025-02-12 02:02 UTC, gonuke commented on src/geometry.cpp
> +  while (true) {
It may be possible to set this up as a while loop for `end_point_distance > cell_boundary_distance`

2025-02-12 02:02 UTC, gonuke commented on tests/unit_tests/test_optical_thickness.py
> +        f"Expected {expected_tau_x}, but got {calculated_tau_x}"
Don't need these strings - pytest should report discrepancies verbosely

2025-02-12 02:02 UTC, gonuke commented on tests/unit_tests/test_optical_thickness.py
> +    mat2_r = 10
Can these be defined in a test fixture and used where necessary throughout? That will allow you to try different values consistently

2025-02-13 03:03 UTC, damianjilk2 commented on src/geometry.cpp
> +  Position start_sampled_position, Position end_sampled_position)
hmm. I wonder why it still runs properly with the header discrepancy. I wonder if it only considers the types and method name rather than the parameter names

2025-02-13 03:09 UTC, damianjilk2 commented on src/geometry.cpp
> +  while (true) {
initializing variables beforehand and setting logic `>=` should successfully implement this

2025-02-24 22:39 UTC, gonuke approved these changes
I haven't run the tests, but I think this looks good.

2025-02-25 16:17 UTC, merged